require('keymaps')
require('plugins.lazy')
require('plugins.nvim-cmp')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.obsidian')
-- require('plugins.trouble')
require('plugins.ai')
require('plugins.zenmode')
